#!/usr/bin/env bash
set -euo pipefail

# ── Configuration ───────────────────────────────────────────────────
# Sourced from /etc/nmtrust/config (generated by NixOS module).
# Safe defaults when running without the module.
TRUSTED_UUIDS=()
EXCLUDED_PATTERNS=()
MANAGED_USERS=()
MIXED_POLICY="untrusted"
EVAL_FAILURE_POLICY="untrusted"

if [[ -f /etc/nmtrust/config ]]; then
  # shellcheck source=/dev/null
  source /etc/nmtrust/config
fi

STATE_DIR="/run/nmtrust"
STATE_FILE="$STATE_DIR/state"
OVERRIDE_FILE="$STATE_DIR/override"

TRUST_TRIGGER="${TRUST_TRIGGER:-manual}"
TRUST_TRIGGER="${TRUST_TRIGGER//[$'\n\r']/}"
TRUST_EVENT="${TRUST_EVENT:-}"
TRUST_EVENT="${TRUST_EVENT//[$'\n\r']/}"

# ── Logging ─────────────────────────────────────────────────────────
log() {
  echo "nmtrust[$$]: $*" >&2
}

# ── Root check ──────────────────────────────────────────────────────
require_root() {
  if [[ "$EUID" -ne 0 ]]; then
    echo "error: nmtrust requires root privileges" >&2
    exit 1
  fi
}

# ── UUID set membership ─────────────────────────────────────────────
is_trusted_uuid() {
  local uuid="$1"
  local u
  for u in "${TRUSTED_UUIDS[@]+"${TRUSTED_UUIDS[@]}"}"; do
    if [[ "$u" == "$uuid" ]]; then
      return 0
    fi
  done
  return 1
}

# ── Excluded connection check (fnmatch-style, FNM_NOESCAPE) ────────
is_excluded() {
  local name="$1"
  local pat
  for pat in "${EXCLUDED_PATTERNS[@]+"${EXCLUDED_PATTERNS[@]}"}"; do
    # shellcheck disable=SC2254
    case "$name" in
      $pat) return 0 ;;
    esac
  done
  return 1
}

# ── D-Bus queries ───────────────────────────────────────────────────
# Populates parallel arrays: CONN_NAMES, CONN_UUIDS, CONN_PATHS
# Returns 0 on success, 1 on D-Bus failure
query_active_connections() {
  CONN_NAMES=()
  CONN_UUIDS=()
  CONN_PATHS=()

  local raw
  if ! raw=$(busctl get-property \
        org.freedesktop.NetworkManager \
        /org/freedesktop/NetworkManager \
        org.freedesktop.NetworkManager \
        ActiveConnections 2>&1); then
    DBUS_ERROR="$raw"
    return 1
  fi

  # Output looks like: ao N "/org/..." "/org/..."
  # Strip the type prefix and parse object paths
  local paths_str
  paths_str=$(echo "$raw" | gawk '{
    # skip first two fields (type "ao" and count)
    for (i = 3; i <= NF; i++) {
      gsub(/"/, "", $i)
      print $i
    }
  }')

  if [[ -z "$paths_str" ]]; then
    # No active connections at all
    return 0
  fi

  local path uuid_raw id_raw uuid id
  while IFS= read -r path; do
    [[ -z "$path" ]] && continue

    if ! uuid_raw=$(busctl get-property \
          org.freedesktop.NetworkManager \
          "$path" \
          org.freedesktop.NetworkManager.Connection.Active \
          Uuid 2>&1); then
      DBUS_ERROR="$uuid_raw"
      return 1
    fi

    if ! id_raw=$(busctl get-property \
          org.freedesktop.NetworkManager \
          "$path" \
          org.freedesktop.NetworkManager.Connection.Active \
          Id 2>&1); then
      DBUS_ERROR="$id_raw"
      return 1
    fi

    # busctl output: s "value"
    uuid=$(echo "$uuid_raw" | gawk '{ gsub(/"/, "", $2); print $2 }')
    id=$(echo "$id_raw" | gawk '{ gsub(/"/, "", $2); print $2 }')

    # Validate UUID format to catch D-Bus parsing failures
    if [[ ! "$uuid" =~ ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ ]]; then
      DBUS_ERROR="malformed UUID from D-Bus: $uuid"
      return 1
    fi

    CONN_PATHS+=("$path")
    CONN_UUIDS+=("$uuid")
    CONN_NAMES+=("$id")
  done <<< "$paths_str"

  return 0
}

# ── Read previous state ─────────────────────────────────────────────
read_previous_state() {
  if [[ -f "$STATE_FILE" ]]; then
    cat "$STATE_FILE"
  else
    echo "unknown"
  fi
}

# ── Write state atomically ──────────────────────────────────────────
write_state() {
  local state="$1"
  local tmp
  tmp=$(mktemp "$STATE_DIR/.state.XXXXXX")
  echo "$state" > "$tmp"
  chmod 0600 "$tmp"
  mv "$tmp" "$STATE_FILE"
}

# ── Read override file ──────────────────────────────────────────────
read_override() {
  if [[ ! -f "$OVERRIDE_FILE" ]]; then
    echo "none"
    return
  fi
  local val
  val=$(cat "$OVERRIDE_FILE")
  case "$val" in
    trusted|untrusted)
      echo "$val"
      ;;
    *)
      log "OVERRIDE_INVALID content=\"$val\""
      echo "invalid"
      ;;
  esac
}

# ── Evaluate trust state ────────────────────────────────────────────
# Sets: COMPUTED_STATE, CONNECTIONS_ACTIVE, CONNECTIONS_TRUSTED,
#        CONNECTIONS_EXCLUDED, OVERRIDE_VAL
evaluate_trust() {
  CONNECTIONS_ACTIVE=0
  CONNECTIONS_TRUSTED=0
  CONNECTIONS_EXCLUDED=0
  DBUS_ERROR=""

  # Check override first
  OVERRIDE_VAL=$(read_override)
  if [[ "$OVERRIDE_VAL" == "trusted" || "$OVERRIDE_VAL" == "untrusted" ]]; then
    COMPUTED_STATE="$OVERRIDE_VAL"
    return 0
  fi
  # invalid override falls through to auto
  if [[ "$OVERRIDE_VAL" == "invalid" ]]; then
    OVERRIDE_VAL="none"
  fi

  # Query D-Bus
  if ! query_active_connections; then
    COMPUTED_STATE="$EVAL_FAILURE_POLICY"
    log "EVAL_FAILURE reason=\"$DBUS_ERROR\" policy=$EVAL_FAILURE_POLICY resolved_state=$COMPUTED_STATE"
    return 0
  fi

  # Categorize connections
  local total=${#CONN_UUIDS[@]}
  local active_names=()
  local active_uuids=()
  local i

  for (( i=0; i<total; i++ )); do
    if is_excluded "${CONN_NAMES[$i]}"; then
      (( CONNECTIONS_EXCLUDED++ )) || true
    else
      active_names+=("${CONN_NAMES[$i]}")
      active_uuids+=("${CONN_UUIDS[$i]}")
    fi
  done

  CONNECTIONS_ACTIVE=${#active_uuids[@]}

  # Determine state
  if [[ "$CONNECTIONS_ACTIVE" -eq 0 ]]; then
    COMPUTED_STATE="offline"
    return 0
  fi

  local trusted_count=0
  for (( i=0; i<CONNECTIONS_ACTIVE; i++ )); do
    if is_trusted_uuid "${active_uuids[$i]}"; then
      (( trusted_count++ )) || true
    fi
  done
  CONNECTIONS_TRUSTED=$trusted_count

  if [[ "$trusted_count" -eq "$CONNECTIONS_ACTIVE" ]]; then
    COMPUTED_STATE="trusted"
  elif [[ "$trusted_count" -eq 0 ]]; then
    COMPUTED_STATE="untrusted"
  else
    # mixed -> resolve via policy
    COMPUTED_STATE="$MIXED_POLICY"
  fi

  return 0
}

# ── Activate targets ────────────────────────────────────────────────
activate_target() {
  local state="$1"
  local target="nmtrust-${state}.target"

  # System target
  systemctl start "$target"

  # User targets
  local user
  for user in "${MANAGED_USERS[@]+"${MANAGED_USERS[@]}"}"; do
    if ! systemctl --user -M "${user}@" start "$target" 2>&1; then
      log "USER_TARGET_FAILED user=$user target=$target"
    fi
  done
}

# ── Subcommand: apply ───────────────────────────────────────────────
cmd_apply() {
  require_root

  evaluate_trust

  local previous_state
  previous_state=$(read_previous_state)

  # Deduplication: no-op if state unchanged
  if [[ "$COMPUTED_STATE" == "$previous_state" ]]; then
    return 0
  fi

  log "TRUST_TRANSITION previous_state=$previous_state new_state=$COMPUTED_STATE trigger=$TRUST_TRIGGER event=${TRUST_EVENT:-none} connections_active=$CONNECTIONS_ACTIVE connections_trusted=$CONNECTIONS_TRUSTED connections_excluded=$CONNECTIONS_EXCLUDED override=$OVERRIDE_VAL"

  write_state "$COMPUTED_STATE"
  activate_target "$COMPUTED_STATE"
}

# ── Subcommand: state ───────────────────────────────────────────────
cmd_state() {
  require_root

  evaluate_trust

  # Determine active target
  local active_target="none"
  local t
  for t in trusted untrusted offline; do
    if systemctl is-active --quiet "nmtrust-${t}.target" 2>/dev/null; then
      active_target="nmtrust-${t}.target"
      break
    fi
  done

  echo "State: $COMPUTED_STATE"
  echo "Override: $OVERRIDE_VAL"
  echo "Active target: $active_target"
  echo "Connections:"

  local total=${#CONN_UUIDS[@]}
  local i
  for (( i=0; i<total; i++ )); do
    local label
    if is_excluded "${CONN_NAMES[$i]}"; then
      label="excluded"
    elif is_trusted_uuid "${CONN_UUIDS[$i]}"; then
      label="trusted"
    else
      label="untrusted"
    fi
    echo "  ${CONN_NAMES[$i]} (${CONN_UUIDS[$i]}) [$label]"
  done
}

# ── Subcommand: override ────────────────────────────────────────────
cmd_override() {
  require_root

  local action="${1:-}"
  case "$action" in
    trusted|untrusted)
      local tmp
      tmp=$(mktemp "$STATE_DIR/.override.XXXXXX")
      echo "$action" > "$tmp"
      chmod 0600 "$tmp"
      mv "$tmp" "$OVERRIDE_FILE"
      log "OVERRIDE_SET state=$action user=$USER"
      echo "Override active: forcing trust state to '$action' (ephemeral, cleared on reboot)"
      systemctl start nmtrust-apply.service
      ;;
    clear)
      if [[ -f "$OVERRIDE_FILE" ]]; then
        rm "$OVERRIDE_FILE"
      fi
      log "OVERRIDE_CLEAR user=$USER"
      echo "Override cleared: returning to automatic trust evaluation"
      systemctl start nmtrust-apply.service
      ;;
    *)
      echo "Usage: nmtrust override {trusted|untrusted|clear}" >&2
      exit 1
      ;;
  esac
}

# ── Subcommand: status ──────────────────────────────────────────────
cmd_status() {
  require_root

  local active_target="none"
  local t
  for t in trusted untrusted offline; do
    if systemctl is-active --quiet "nmtrust-${t}.target" 2>/dev/null; then
      active_target="nmtrust-${t}.target"
      break
    fi
  done

  echo "Active target: $active_target"
  echo ""

  for t in trusted untrusted offline; do
    local target="nmtrust-${t}.target"
    echo "=== $target ==="
    # List units bound to this target
    local deps
    if deps=$(systemctl list-dependencies "$target" --plain 2>/dev/null); then
      if [[ -n "$deps" ]]; then
        while IFS= read -r unit; do
          [[ -z "$unit" ]] && continue
          # Skip the target itself
          [[ "$unit" == "$target" ]] && continue
          local unit_state
          unit_state=$(systemctl is-active "$unit" 2>/dev/null || true)
          echo "  $unit ($unit_state)"
        done <<< "$deps"
      fi
    fi
    echo ""
  done
}

# ── Main dispatch ───────────────────────────────────────────────────
subcmd="${1:-}"
shift || true

case "$subcmd" in
  state)    cmd_state "$@" ;;
  apply)    cmd_apply "$@" ;;
  override) cmd_override "$@" ;;
  status)   cmd_status "$@" ;;
  *)
    echo "Usage: nmtrust {state|apply|override|status}" >&2
    exit 1
    ;;
esac
