# pkgs/by-name/nm/nmtrust/package.nix
#
# Declarative network trust management for NixOS. The script reads its
# configuration at runtime from /etc/nmtrust/config (generated by the
# NixOS module). The package itself carries no baked-in config.

{
  lib,
  stdenv,
  fetchFromGitHub,
  makeWrapper,
  shellcheck,
  systemd,
  coreutils,
  gawk,
  util-linux,
}:

stdenv.mkDerivation {
  pname = "nmtrust";
  version = "0.1.0";

  src = fetchFromGitHub {
    owner = "brett";
    repo = "nmtrust-nix";
    rev = "v0.1.0";
    hash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
  };

  nativeBuildInputs = [ makeWrapper ];
  nativeCheckInputs = [ shellcheck ];

  doCheck = true;
  checkPhase = ''
    runHook preCheck
    shellcheck nmtrust.sh
    runHook postCheck
  '';

  installPhase = ''
    runHook preInstall
    install -Dm755 nmtrust.sh $out/bin/nmtrust
    wrapProgram $out/bin/nmtrust \
      --prefix PATH : ${
        lib.makeBinPath [
          systemd
          coreutils
          gawk
          util-linux
        ]
      }
    runHook postInstall
  '';

  meta = {
    description = "Declarative network trust management for NixOS";
    longDescription = ''
      nmtrust evaluates the trust state of active NetworkManager connections
      and activates corresponding systemd targets. Services bound to these
      targets start and stop automatically as you move between trusted,
      untrusted, and offline networks.

      A NixOS-native reimplementation of nmtrust by Peter Hogg (pigmonkey).
    '';
    homepage = "https://github.com/brett/nmtrust-nix";
    license = lib.licenses.unlicense;
    maintainers = [ ]; # Add your nixpkgs maintainer handle here
    mainProgram = "nmtrust";
    platforms = lib.platforms.linux;
  };
}
